// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Chain struct {
	ID             string `json:"id"`
	Key            string `json:"key"`
	ChainID        string `json:"chain_id"`
	RPCAddr        string `json:"rpc_addr"`
	AccountPrefix  string `json:"account_prefix"`
	Gas            int    `json:"gas"`
	GasPrices      string `json:"gas_prices"`
	DefaultDenom   string `json:"default_denom"`
	TrustingPeriod string `json:"trusting_period"`
}

type ChainStatus struct {
	Name       string      `json:"name"`
	Reachable  *bool       `json:"reachable"`
	Height     string      `json:"height"`
	Client     *Client     `json:"client"`
	Connection *Connection `json:"connection"`
	Channel    *Channel    `json:"channel"`
}

type Channel struct {
	ID    string `json:"id"`
	Port  string `json:"port"`
	State string `json:"state"`
	Order string `json:"order"`
}

type Client struct {
	ID     string `json:"id"`
	Height string `json:"height"`
}

type Config struct {
	Global []*Kv    `json:"global"`
	Chains []*Chain `json:"chains"`
	Paths  []*Path  `json:"paths"`
}

type Connection struct {
	ID    string `json:"id"`
	State string `json:"state"`
}

type Kv struct {
	Key   string  `json:"key"`
	Value *string `json:"value"`
}

type Message struct {
	ID        string    `json:"id"`
	Text      string    `json:"text"`
	CreatedBy string    `json:"createdBy"`
	CreatedAt time.Time `json:"createdAt"`
}

type Path struct {
	ID       string       `json:"id"`
	Name     string       `json:"name"`
	Src      *PathContent `json:"src"`
	Dst      *PathContent `json:"dst"`
	Strategy *Strategy    `json:"strategy"`
}

type PathContent struct {
	ChainID      string `json:"chain_id"`
	ClientID     string `json:"client_id"`
	ConnectionID string `json:"connection_id"`
	ChannelID    string `json:"channel_id"`
	PortID       string `json:"port_id"`
	Order        string `json:"order"`
}

type PathStatus struct {
	Src *ChainStatus `json:"src"`
	Dst *ChainStatus `json:"dst"`
}

type Strategy struct {
	Type string `json:"type"`
}

type Version struct {
	Version   string `json:"version"`
	Commit    string `json:"commit"`
	CosmosSdk string `json:"cosmos_sdk"`
	Gaia      string `json:"gaia"`
	Go        string `json:"go"`
}
